---
# tasks file for ec2

- name: "Launching Kubernetes Master Node Instance in AWS using Ansible"
  ec2:
    key_name: "mynewawskey"
    instance_tags:
      Name: masterNode
    instance_type: "t2.micro"
    image: "ami-045e6fa7127ab1ac4"
    wait: yes
    count: 1
    vpc_subnet_id: "subnet-d7caf0bf"
    assign_public_ip: yes
    region: "ap-south-1"
    state: present
    group_id: "sg-0a26278386f9f22fa"
    aws_access_key: "{{my_user}}"
    aws_secret_key: "{{my_pass}}"

- name: "Launching Kubernetes Slave Node Instances in AWS using Ansible"
  ec2:
    key_name: "mynewawskey"
    instance_tags:
      Name: slaveNode
    instance_type: "t2.micro"
    image: "ami-045e6fa7127ab1ac4"
    wait: yes
    count: 2
    vpc_subnet_id: "subnet-d7caf0bf"
    assign_public_ip: yes
    region: "ap-south-1"
    state: present
    group_id: "sg-0a26278386f9f22fa"
    aws_access_key: "{{my_user}}"
    aws_secret_key: "{{my_pass}}"

- name: Refreshing inventory for new instances to come into the updated inventory
  meta: refresh_inventory
